/**
 *
 * we can remove this file  after API intergation
 */

export default [
  {
    id: 1,
    firstName: "E.",
    lastName: "Rogers789012345678",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 2,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Patient declined",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 3,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Prospective",
    caseDetails: "Patient decision pending",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 4,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Prospective",
    caseDetails: "Awaiting patient payment",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 5,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Pending",
    caseDetails: "Awaiting doctor approval",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 6,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Pending",
    caseDetails: "Under quality check",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 7,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Pending",
    caseDetails: "Needs doctor review",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 8,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "",
    orderSatus: "In production",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 9,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "",
    orderSatus: "Shipped",
    dentalMonitoring: "Not started",
    lastMonitoringScan: "01/05/2023",
  },
  {
    id: 10,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "",
    orderSatus: "Delivered",
    dentalMonitoring: "Tracking",
    lastMonitoringScan: "01/05/2023",
  },
  {
    id: 11,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "",
    orderSatus: "Delivered",
    dentalMonitoring: "Not started",
    lastMonitoringScan: "01/05/2023",
  },
  {
    id: 12,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "",
    orderSatus: "Retainers sent",
    dentalMonitoring: "Not tracking",
    lastMonitoringScan: "",
  },
  {
    id: 13,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Prospective",
    caseDetails: "Needs cleaning",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 14,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Prospective",
    caseDetails: "Temporary health issue",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
  {
    id: 15,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Permanent health issue",
    orderSatus: "",
    dentalMonitoring: "",
    lastMonitoringScan: "",
  },
];
