/**
 *
 * we can remove this file  after API intergation
 */

export default [
  {
    id: 1,
    first_name: "E.",
    last_name: "Rogers789012345678",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "Case too complex",
    order_status: "Retainers sent",
    dental_monitoring: "Tracking",
    last_monitoring: "",
  },
  {
    id: 2,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "Patient declined",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 3,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Prospective",
    case_detail: "Patient decision pending",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 4,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Prospective",
    case_detail: "Awaiting patient payment",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 5,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Pending",
    case_detail: "Awaiting doctor approval",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 6,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Active",
    case_detail: "Under quality check",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 7,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Pending",
    case_detail: "Needs doctor review",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 8,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Completed",
    case_detail: "",
    order_status: "In production",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 9,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "",
    order_status: "Shipped",
    dental_monitoring: "Not started",
    last_monitoring: "01/05/2023",
  },
  {
    id: 10,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "",
    order_status: "Delivered",
    dental_monitoring: "Tracking",
    last_monitoring: "01/05/2023",
  },
  {
    id: 11,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "",
    order_status: "Delivered",
    dental_monitoring: "Not started",
    last_monitoring: "01/05/2023",
  },
  {
    id: 12,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "",
    order_status: "Retainers sent",
    dental_monitoring: "Not tracking",
    last_monitoring: "",
  },
  {
    id: 13,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Prospective",
    case_detail: "Needs cleaning",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 14,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Prospective",
    case_detail: "Temporary health issue",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
  {
    id: 15,
    first_name: "E.",
    last_name: "Rogers",
    patient_dob: "09/08/1985",
    status: "Rejected",
    case_detail: "Permanent health issue",
    order_status: "",
    dental_monitoring: "",
    last_monitoring: "",
  },
];
