apiVersion: v1
kind: Service
metadata:
  name: pro-portal
  namespace: public
  labels:
    app: pro-portal
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: copa-pro-portal
