/**
 *
 * we can remove this file  after API intergation
 */

export default [
  {
    id: 1,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 2,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 3,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 4,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting patient payment",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 5,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting doctor approval",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 6,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 7,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 8,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 9,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting patient payment",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 10,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting doctor approval",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 11,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 12,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 13,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 14,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting patient payment",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 15,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting doctor approval",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 1,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 2,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 3,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 4,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting patient payment",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 5,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting doctor approval",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 6,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 7,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 8,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 9,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting patient payment",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 10,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Awaiting doctor approval",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 11,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 12,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
  {
    id: 13,
    firstName: "E.",
    lastName: "Rogers",
    dateOfBirth: "09/08/1985",
    patientStatus: "Rejected",
    caseDetails: "Case too complex",
    orderSatus: "inproduction",
    dentalMonitoring: "Tracking",
    lasMonitoringScan: "01/05/2023",
  },
];
