apiVersion: v1
kind: Service
metadata:
  name: user-service-v1
  namespace: development
  labels:
    app: user-service-v1
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8000
      protocol: TCP
  selector:
    app: user-service-v1